### ISSUE TITLE
Add select day's images to auto-generated entry OR prompt user through gallery view

### ISSUE THREAD

**Issue by heysivani** [wardsquid/journal#14]
Need to decide which way is most viable + best for UX

- [x] Tap button to select image from phone gallery, if no image has already been selected

- [x] Given that I took pictures that day and uploaded to my entry, then I expect to see those pictures in my entry.

- [x] Given that I didn’t take pictures that day, then I expect to see a default image/default text saying “no images taken” in my entry instead.

**Comment by Jaymontojo** [comment]
currently this works by user uploading an image via a button. I will leave this issue open 

**Clarification** 
currently a default image is displayed at the top of the entry
if a user has a photo is this automatically replaced?
