### ISSUE TITLE
Auto-generated text input for people detected in images

### ISSUE THREAD

**Issue by heysivani** [wardsquid/journal#16]
- [ ] Given that my pictures contained faces, then I expect to see an extra line in my entry where I can enter those people’s names.

- [ ] Implement using mlkit via firebase cloud functions to analyze a user's image(s) and tell us how many faces were detected.

**Comment by Jaymontojo** [comment]
This is done, Also implemented detection and autogenerated text for other labels aside from people. 
Implemented by Jay and Yoshi 12/2/2020 approved by Antonio
