### ISSUE TITLE
Set a daily reminder for a push notification

### ISSUE THREAD

**Issue by heysivani** [wardsquid/journal#22]
- [x] Given that I see my <some screen - where would be best?>, when I click on set reminder, I am able to add a reminder for a specific time to alert me everyday.

- [x] Given that I have my phone, when it’s my reminder time, then I receive a push alert on my phone reminding me to add to my entry.

- [x] Need to store this reminder time in the user's info in firestore

- [x] Daily notification every 24 hours from firebase if you haven't opened the app

**Comment by Jaymontojo** [comment]
Added Antonio. Looks like he was able to set the reminder to pop up.

If its set on a daily timer, then I think we can close this!

**Comment by Jaymontojo** [comment]
Implemented by Sivani 12/1/2020 merged by Jay(?)

I think we can close this one right?
